//! Generated by AEROST from executable AIR. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SupervisorState {
    Initializing,
    Normal,
    EnergyConservation,
    Degraded,
    Critical,
    RecoveryPending,
    Lockout,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Inputs {
    pub input_set_valid: bool,
    pub initialization_complete: bool,
    pub battery_a_healthy: bool,
    pub battery_b_healthy: bool,
    pub essential_power_available: bool,
    pub main_bus_warning_persisted: bool,
    pub main_bus_critical: bool,
    pub reserve_energy_low: bool,
    pub return_energy_insufficient: bool,
    pub contactor_mismatch_persisted: bool,
    pub recovery_stable: bool,
    pub reset_authorized: bool,
    pub payload_overcurrent: bool,
    pub flight_phase_landing: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Outputs {
    pub payload_permit: bool,
    pub shed_nonessential_loads: bool,
    pub isolate_battery_a: bool,
    pub isolate_battery_b: bool,
    pub return_to_home_request: bool,
    pub immediate_landing_request: bool,
    pub mission_progression_permit: bool,
    pub blocking_power_fault: bool,
    pub supervisor_state: SupervisorState,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Retained {
    pub state: SupervisorState,
    pub blocking_fault_latched: bool,
}

impl Default for Inputs {
    fn default() -> Self {
        Self {
            input_set_valid: false,
            initialization_complete: false,
            battery_a_healthy: false,
            battery_b_healthy: false,
            essential_power_available: false,
            main_bus_warning_persisted: false,
            main_bus_critical: false,
            reserve_energy_low: false,
            return_energy_insufficient: false,
            contactor_mismatch_persisted: false,
            recovery_stable: false,
            reset_authorized: false,
            payload_overcurrent: false,
            flight_phase_landing: false,
        }
    }
}

impl Default for Outputs {
    fn default() -> Self {
        Self {
            payload_permit: false,
            shed_nonessential_loads: false,
            isolate_battery_a: false,
            isolate_battery_b: false,
            return_to_home_request: false,
            immediate_landing_request: false,
            mission_progression_permit: false,
            blocking_power_fault: false,
            supervisor_state: SupervisorState::Initializing,
        }
    }
}

impl Default for Retained {
    fn default() -> Self {
        Self {
            state: SupervisorState::Initializing,
            blocking_fault_latched: false,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct DecisionEvent { pub id: &'static str, pub result: bool, pub conditions: Vec<(&'static str, bool)> }
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Trace { pub statements: Vec<&'static str>, pub decisions: Vec<DecisionEvent>, pub case_arms: Vec<&'static str>, pub diagnostics: Vec<&'static str> }
#[derive(Clone, Debug, PartialEq)]
pub struct CycleResult { pub retained: Retained, pub outputs: Outputs, pub normal_commit_inhibited: bool, pub trace: Trace }

pub fn step(mut state: Retained, inputs: &Inputs, blocking_runtime_fault: bool) -> CycleResult {
    let resident = state.clone();
    let mut outputs = Outputs::default();
    let mut trace = Trace::default();
    // AEROST-ID: AIR-STMT-E87BE3D9122E
    trace.statements.push("AIR-STMT-E87BE3D9122E");
    let air_dec_eb272a2d98bb_c0 = inputs.input_set_valid;
    let air_dec_eb272a2d98bb_result = inputs.input_set_valid;
    trace.decisions.push(DecisionEvent { id: "AIR-DEC-EB272A2D98BB", result: air_dec_eb272a2d98bb_result, conditions: vec![("AIR-COND-EFE56C86C850", air_dec_eb272a2d98bb_c0)] });
    if air_dec_eb272a2d98bb_result {
        // AEROST-ID: AIR-STMT-22EA36CE7782
        trace.statements.push("AIR-STMT-22EA36CE7782");
        match state.state {
            SupervisorState::Initializing => {
                trace.case_arms.push("AIR-STMT-22EA36CE7782::INITIALIZING");
                // AEROST-ID: AIR-STMT-BCE73FB5DDAD
                trace.statements.push("AIR-STMT-BCE73FB5DDAD");
                let air_dec_a2a44279a13d_c0 = inputs.initialization_complete;
                let air_dec_a2a44279a13d_c1 = inputs.battery_a_healthy;
                let air_dec_a2a44279a13d_c2 = inputs.battery_b_healthy;
                let air_dec_a2a44279a13d_c3 = inputs.essential_power_available;
                let air_dec_a2a44279a13d_result = inputs.initialization_complete && (inputs.battery_a_healthy || inputs.battery_b_healthy) && inputs.essential_power_available;
                trace.decisions.push(DecisionEvent { id: "AIR-DEC-A2A44279A13D", result: air_dec_a2a44279a13d_result, conditions: vec![("AIR-COND-46486C3E7B4D", air_dec_a2a44279a13d_c0), ("AIR-COND-B1E7AF6F9325", air_dec_a2a44279a13d_c1), ("AIR-COND-933AFAC55E2F", air_dec_a2a44279a13d_c2), ("AIR-COND-D765DACDD027", air_dec_a2a44279a13d_c3)] });
                if air_dec_a2a44279a13d_result {
                    // AEROST-ID: AIR-STMT-4852C2496F28
                    trace.statements.push("AIR-STMT-4852C2496F28");
                    state.state = SupervisorState::Normal;
                } else {
                    let air_dec_bbc0832c9670_c0 = inputs.initialization_complete;
                    let air_dec_bbc0832c9670_result = inputs.initialization_complete;
                    trace.decisions.push(DecisionEvent { id: "AIR-DEC-BBC0832C9670", result: air_dec_bbc0832c9670_result, conditions: vec![("AIR-COND-824107AE33E7", air_dec_bbc0832c9670_c0)] });
                    if air_dec_bbc0832c9670_result {
                        // AEROST-ID: AIR-STMT-6D50A2C7A880
                        trace.statements.push("AIR-STMT-6D50A2C7A880");
                        state.state = SupervisorState::Lockout;
                    } else {
                    }
                }
            },
            SupervisorState::Normal => {
                trace.case_arms.push("AIR-STMT-22EA36CE7782::NORMAL");
                // AEROST-ID: AIR-STMT-6F7682246674
                trace.statements.push("AIR-STMT-6F7682246674");
                let air_dec_8c1aaf3c5949_c0 = !inputs.battery_a_healthy;
                let air_dec_8c1aaf3c5949_c1 = !inputs.battery_b_healthy;
                let air_dec_8c1aaf3c5949_result = !inputs.battery_a_healthy && !inputs.battery_b_healthy;
                trace.decisions.push(DecisionEvent { id: "AIR-DEC-8C1AAF3C5949", result: air_dec_8c1aaf3c5949_result, conditions: vec![("AIR-COND-63B49803733D", air_dec_8c1aaf3c5949_c0), ("AIR-COND-14A07CAD6C04", air_dec_8c1aaf3c5949_c1)] });
                if air_dec_8c1aaf3c5949_result {
                    // AEROST-ID: AIR-STMT-80CDAC22F297
                    trace.statements.push("AIR-STMT-80CDAC22F297");
                    let air_dec_fd89dc1c5add_c0 = inputs.essential_power_available;
                    let air_dec_fd89dc1c5add_result = inputs.essential_power_available;
                    trace.decisions.push(DecisionEvent { id: "AIR-DEC-FD89DC1C5ADD", result: air_dec_fd89dc1c5add_result, conditions: vec![("AIR-COND-5A81CE40A399", air_dec_fd89dc1c5add_c0)] });
                    if air_dec_fd89dc1c5add_result {
                        // AEROST-ID: AIR-STMT-53159465EEC7
                        trace.statements.push("AIR-STMT-53159465EEC7");
                        state.state = SupervisorState::Critical;
                    } else {
                        // AEROST-ID: AIR-STMT-5F2EDC425EF8
                        trace.statements.push("AIR-STMT-5F2EDC425EF8");
                        state.state = SupervisorState::Lockout;
                    }
                } else {
                    let air_dec_47ba8aadec39_c0 = inputs.main_bus_critical;
                    let air_dec_47ba8aadec39_result = inputs.main_bus_critical;
                    trace.decisions.push(DecisionEvent { id: "AIR-DEC-47BA8AADEC39", result: air_dec_47ba8aadec39_result, conditions: vec![("AIR-COND-0E4BEDA3E54F", air_dec_47ba8aadec39_c0)] });
                    if air_dec_47ba8aadec39_result {
                        // AEROST-ID: AIR-STMT-3C7AB5CB87EA
                        trace.statements.push("AIR-STMT-3C7AB5CB87EA");
                        state.state = SupervisorState::Critical;
                    } else {
                        let air_dec_a4965ea0089c_c0 = inputs.return_energy_insufficient;
                        let air_dec_a4965ea0089c_result = inputs.return_energy_insufficient;
                        trace.decisions.push(DecisionEvent { id: "AIR-DEC-A4965EA0089C", result: air_dec_a4965ea0089c_result, conditions: vec![("AIR-COND-CC86694FC691", air_dec_a4965ea0089c_c0)] });
                        if air_dec_a4965ea0089c_result {
                            // AEROST-ID: AIR-STMT-EFFC6318F22A
                            trace.statements.push("AIR-STMT-EFFC6318F22A");
                            state.state = SupervisorState::EnergyConservation;
                        } else {
                            let air_dec_ca16fedc06f6_c0 = inputs.contactor_mismatch_persisted;
                            let air_dec_ca16fedc06f6_c1 = inputs.main_bus_warning_persisted;
                            let air_dec_ca16fedc06f6_c2 = !inputs.battery_a_healthy;
                            let air_dec_ca16fedc06f6_c3 = !inputs.battery_b_healthy;
                            let air_dec_ca16fedc06f6_result = inputs.contactor_mismatch_persisted || inputs.main_bus_warning_persisted || !inputs.battery_a_healthy || !inputs.battery_b_healthy;
                            trace.decisions.push(DecisionEvent { id: "AIR-DEC-CA16FEDC06F6", result: air_dec_ca16fedc06f6_result, conditions: vec![("AIR-COND-69E1E0C7E3C9", air_dec_ca16fedc06f6_c0), ("AIR-COND-9C40B9684FA7", air_dec_ca16fedc06f6_c1), ("AIR-COND-A9AACEB02838", air_dec_ca16fedc06f6_c2), ("AIR-COND-8BBE51FE9300", air_dec_ca16fedc06f6_c3)] });
                            if air_dec_ca16fedc06f6_result {
                                // AEROST-ID: AIR-STMT-363BB5F7BABB
                                trace.statements.push("AIR-STMT-363BB5F7BABB");
                                state.state = SupervisorState::Degraded;
                            } else {
                                let air_dec_d12f80732d65_c0 = inputs.reserve_energy_low;
                                let air_dec_d12f80732d65_result = inputs.reserve_energy_low;
                                trace.decisions.push(DecisionEvent { id: "AIR-DEC-D12F80732D65", result: air_dec_d12f80732d65_result, conditions: vec![("AIR-COND-995C9A8B876E", air_dec_d12f80732d65_c0)] });
                                if air_dec_d12f80732d65_result {
                                    // AEROST-ID: AIR-STMT-448508E90F1C
                                    trace.statements.push("AIR-STMT-448508E90F1C");
                                    state.state = SupervisorState::EnergyConservation;
                                } else {
                                }
                            }
                        }
                    }
                }
            },
            SupervisorState::EnergyConservation => {
                trace.case_arms.push("AIR-STMT-22EA36CE7782::ENERGY_CONSERVATION");
                // AEROST-ID: AIR-STMT-1CB70230AF67
                trace.statements.push("AIR-STMT-1CB70230AF67");
                let air_dec_9a422b741657_c0 = !inputs.battery_a_healthy;
                let air_dec_9a422b741657_c1 = !inputs.battery_b_healthy;
                let air_dec_9a422b741657_result = !inputs.battery_a_healthy && !inputs.battery_b_healthy;
                trace.decisions.push(DecisionEvent { id: "AIR-DEC-9A422B741657", result: air_dec_9a422b741657_result, conditions: vec![("AIR-COND-66F919A4468C", air_dec_9a422b741657_c0), ("AIR-COND-00908D0AC570", air_dec_9a422b741657_c1)] });
                if air_dec_9a422b741657_result {
                    // AEROST-ID: AIR-STMT-324860089FA3
                    trace.statements.push("AIR-STMT-324860089FA3");
                    let air_dec_9bbfbe456c16_c0 = inputs.essential_power_available;
                    let air_dec_9bbfbe456c16_result = inputs.essential_power_available;
                    trace.decisions.push(DecisionEvent { id: "AIR-DEC-9BBFBE456C16", result: air_dec_9bbfbe456c16_result, conditions: vec![("AIR-COND-5B282D6B19D0", air_dec_9bbfbe456c16_c0)] });
                    if air_dec_9bbfbe456c16_result {
                        // AEROST-ID: AIR-STMT-502BF6714318
                        trace.statements.push("AIR-STMT-502BF6714318");
                        state.state = SupervisorState::Critical;
                    } else {
                        // AEROST-ID: AIR-STMT-2B029DE35DDA
                        trace.statements.push("AIR-STMT-2B029DE35DDA");
                        state.state = SupervisorState::Lockout;
                    }
                } else {
                    let air_dec_a01e6cfc8f35_c0 = inputs.main_bus_critical;
                    let air_dec_a01e6cfc8f35_result = inputs.main_bus_critical;
                    trace.decisions.push(DecisionEvent { id: "AIR-DEC-A01E6CFC8F35", result: air_dec_a01e6cfc8f35_result, conditions: vec![("AIR-COND-BC1A60139F1A", air_dec_a01e6cfc8f35_c0)] });
                    if air_dec_a01e6cfc8f35_result {
                        // AEROST-ID: AIR-STMT-A648EBCC4774
                        trace.statements.push("AIR-STMT-A648EBCC4774");
                        state.state = SupervisorState::Critical;
                    } else {
                        let air_dec_40b6217c7a61_c0 = inputs.contactor_mismatch_persisted;
                        let air_dec_40b6217c7a61_c1 = inputs.main_bus_warning_persisted;
                        let air_dec_40b6217c7a61_c2 = !inputs.battery_a_healthy;
                        let air_dec_40b6217c7a61_c3 = !inputs.battery_b_healthy;
                        let air_dec_40b6217c7a61_result = inputs.contactor_mismatch_persisted || inputs.main_bus_warning_persisted || !inputs.battery_a_healthy || !inputs.battery_b_healthy;
                        trace.decisions.push(DecisionEvent { id: "AIR-DEC-40B6217C7A61", result: air_dec_40b6217c7a61_result, conditions: vec![("AIR-COND-BABD48A64B79", air_dec_40b6217c7a61_c0), ("AIR-COND-7E3F9A986A6A", air_dec_40b6217c7a61_c1), ("AIR-COND-36B0D097C415", air_dec_40b6217c7a61_c2), ("AIR-COND-679C2BD98047", air_dec_40b6217c7a61_c3)] });
                        if air_dec_40b6217c7a61_result {
                            // AEROST-ID: AIR-STMT-94E73C63A6B1
                            trace.statements.push("AIR-STMT-94E73C63A6B1");
                            state.state = SupervisorState::Degraded;
                        } else {
                            let air_dec_602c491ce204_c0 = !inputs.reserve_energy_low;
                            let air_dec_602c491ce204_c1 = !inputs.return_energy_insufficient;
                            let air_dec_602c491ce204_result = !inputs.reserve_energy_low && !inputs.return_energy_insufficient;
                            trace.decisions.push(DecisionEvent { id: "AIR-DEC-602C491CE204", result: air_dec_602c491ce204_result, conditions: vec![("AIR-COND-A60A2BD8F2FD", air_dec_602c491ce204_c0), ("AIR-COND-B75BA1081948", air_dec_602c491ce204_c1)] });
                            if air_dec_602c491ce204_result {
                                // AEROST-ID: AIR-STMT-601550396FEE
                                trace.statements.push("AIR-STMT-601550396FEE");
                                state.state = SupervisorState::Normal;
                            } else {
                            }
                        }
                    }
                }
            },
            SupervisorState::Degraded => {
                trace.case_arms.push("AIR-STMT-22EA36CE7782::DEGRADED");
                // AEROST-ID: AIR-STMT-E79B42D9F9AB
                trace.statements.push("AIR-STMT-E79B42D9F9AB");
                let air_dec_e154c6b87ffb_c0 = !inputs.battery_a_healthy;
                let air_dec_e154c6b87ffb_c1 = !inputs.battery_b_healthy;
                let air_dec_e154c6b87ffb_result = !inputs.battery_a_healthy && !inputs.battery_b_healthy;
                trace.decisions.push(DecisionEvent { id: "AIR-DEC-E154C6B87FFB", result: air_dec_e154c6b87ffb_result, conditions: vec![("AIR-COND-817FF4A2CA56", air_dec_e154c6b87ffb_c0), ("AIR-COND-C14F85047E54", air_dec_e154c6b87ffb_c1)] });
                if air_dec_e154c6b87ffb_result {
                    // AEROST-ID: AIR-STMT-742539D6F747
                    trace.statements.push("AIR-STMT-742539D6F747");
                    let air_dec_9f38aa8d783b_c0 = inputs.essential_power_available;
                    let air_dec_9f38aa8d783b_result = inputs.essential_power_available;
                    trace.decisions.push(DecisionEvent { id: "AIR-DEC-9F38AA8D783B", result: air_dec_9f38aa8d783b_result, conditions: vec![("AIR-COND-FB54F2EE1373", air_dec_9f38aa8d783b_c0)] });
                    if air_dec_9f38aa8d783b_result {
                        // AEROST-ID: AIR-STMT-B7A45416CCD0
                        trace.statements.push("AIR-STMT-B7A45416CCD0");
                        state.state = SupervisorState::Critical;
                    } else {
                        // AEROST-ID: AIR-STMT-C3992B293712
                        trace.statements.push("AIR-STMT-C3992B293712");
                        state.state = SupervisorState::Lockout;
                    }
                } else {
                    let air_dec_2bf8d2d61b9a_c0 = inputs.main_bus_critical;
                    let air_dec_2bf8d2d61b9a_c1 = inputs.return_energy_insufficient;
                    let air_dec_2bf8d2d61b9a_result = inputs.main_bus_critical || inputs.return_energy_insufficient;
                    trace.decisions.push(DecisionEvent { id: "AIR-DEC-2BF8D2D61B9A", result: air_dec_2bf8d2d61b9a_result, conditions: vec![("AIR-COND-D2D9B19380C7", air_dec_2bf8d2d61b9a_c0), ("AIR-COND-BA77AC6CEF43", air_dec_2bf8d2d61b9a_c1)] });
                    if air_dec_2bf8d2d61b9a_result {
                        // AEROST-ID: AIR-STMT-FCC6F3D279F7
                        trace.statements.push("AIR-STMT-FCC6F3D279F7");
                        state.state = SupervisorState::Critical;
                    } else {
                        let air_dec_0d2b6d2854bb_c0 = inputs.recovery_stable;
                        let air_dec_0d2b6d2854bb_c1 = !inputs.contactor_mismatch_persisted;
                        let air_dec_0d2b6d2854bb_c2 = !inputs.main_bus_warning_persisted;
                        let air_dec_0d2b6d2854bb_c3 = inputs.battery_a_healthy;
                        let air_dec_0d2b6d2854bb_c4 = inputs.battery_b_healthy;
                        let air_dec_0d2b6d2854bb_c5 = inputs.essential_power_available;
                        let air_dec_0d2b6d2854bb_result = inputs.recovery_stable && !inputs.contactor_mismatch_persisted && !inputs.main_bus_warning_persisted && (inputs.battery_a_healthy || inputs.battery_b_healthy) && inputs.essential_power_available;
                        trace.decisions.push(DecisionEvent { id: "AIR-DEC-0D2B6D2854BB", result: air_dec_0d2b6d2854bb_result, conditions: vec![("AIR-COND-E9CE4594367D", air_dec_0d2b6d2854bb_c0), ("AIR-COND-E627EE416F1A", air_dec_0d2b6d2854bb_c1), ("AIR-COND-3BDC2757859D", air_dec_0d2b6d2854bb_c2), ("AIR-COND-DC2862148359", air_dec_0d2b6d2854bb_c3), ("AIR-COND-83F3B5EB4933", air_dec_0d2b6d2854bb_c4), ("AIR-COND-15F32731B053", air_dec_0d2b6d2854bb_c5)] });
                        if air_dec_0d2b6d2854bb_result {
                            // AEROST-ID: AIR-STMT-B5D2E3D5D648
                            trace.statements.push("AIR-STMT-B5D2E3D5D648");
                            state.state = SupervisorState::RecoveryPending;
                        } else {
                        }
                    }
                }
            },
            SupervisorState::Critical => {
                trace.case_arms.push("AIR-STMT-22EA36CE7782::CRITICAL");
                // AEROST-ID: AIR-STMT-77E05FA86735
                trace.statements.push("AIR-STMT-77E05FA86735");
                let air_dec_bb5e24035c0c_c0 = !inputs.battery_a_healthy;
                let air_dec_bb5e24035c0c_c1 = !inputs.battery_b_healthy;
                let air_dec_bb5e24035c0c_c2 = !inputs.essential_power_available;
                let air_dec_bb5e24035c0c_result = !inputs.battery_a_healthy && !inputs.battery_b_healthy && !inputs.essential_power_available;
                trace.decisions.push(DecisionEvent { id: "AIR-DEC-BB5E24035C0C", result: air_dec_bb5e24035c0c_result, conditions: vec![("AIR-COND-E13100E69473", air_dec_bb5e24035c0c_c0), ("AIR-COND-C9A77B0A56A4", air_dec_bb5e24035c0c_c1), ("AIR-COND-BB61825D52A7", air_dec_bb5e24035c0c_c2)] });
                if air_dec_bb5e24035c0c_result {
                    // AEROST-ID: AIR-STMT-2682265396A7
                    trace.statements.push("AIR-STMT-2682265396A7");
                    state.state = SupervisorState::Lockout;
                } else {
                    let air_dec_865460dd81c4_c0 = inputs.recovery_stable;
                    let air_dec_865460dd81c4_c1 = !inputs.main_bus_critical;
                    let air_dec_865460dd81c4_c2 = !inputs.contactor_mismatch_persisted;
                    let air_dec_865460dd81c4_c3 = !inputs.main_bus_warning_persisted;
                    let air_dec_865460dd81c4_c4 = !inputs.return_energy_insufficient;
                    let air_dec_865460dd81c4_c5 = inputs.battery_a_healthy;
                    let air_dec_865460dd81c4_c6 = inputs.battery_b_healthy;
                    let air_dec_865460dd81c4_c7 = inputs.essential_power_available;
                    let air_dec_865460dd81c4_result = inputs.recovery_stable && !inputs.main_bus_critical && !inputs.contactor_mismatch_persisted && !inputs.main_bus_warning_persisted && !inputs.return_energy_insufficient && (inputs.battery_a_healthy || inputs.battery_b_healthy) && inputs.essential_power_available;
                    trace.decisions.push(DecisionEvent { id: "AIR-DEC-865460DD81C4", result: air_dec_865460dd81c4_result, conditions: vec![("AIR-COND-40809FD7BD8C", air_dec_865460dd81c4_c0), ("AIR-COND-A47FB4F62113", air_dec_865460dd81c4_c1), ("AIR-COND-79C6E960DBD5", air_dec_865460dd81c4_c2), ("AIR-COND-741536FE89BA", air_dec_865460dd81c4_c3), ("AIR-COND-6FC64088584E", air_dec_865460dd81c4_c4), ("AIR-COND-144BC0B8AB3F", air_dec_865460dd81c4_c5), ("AIR-COND-D3BFA46CC2AB", air_dec_865460dd81c4_c6), ("AIR-COND-EE98B9F464DC", air_dec_865460dd81c4_c7)] });
                    if air_dec_865460dd81c4_result {
                        // AEROST-ID: AIR-STMT-EAED9383D904
                        trace.statements.push("AIR-STMT-EAED9383D904");
                        state.state = SupervisorState::RecoveryPending;
                    } else {
                    }
                }
            },
            SupervisorState::RecoveryPending => {
                trace.case_arms.push("AIR-STMT-22EA36CE7782::RECOVERY_PENDING");
                // AEROST-ID: AIR-STMT-84CF0E9E7908
                trace.statements.push("AIR-STMT-84CF0E9E7908");
                let air_dec_2a128cf8d3bb_c0 = !inputs.battery_a_healthy;
                let air_dec_2a128cf8d3bb_c1 = !inputs.battery_b_healthy;
                let air_dec_2a128cf8d3bb_result = !inputs.battery_a_healthy && !inputs.battery_b_healthy;
                trace.decisions.push(DecisionEvent { id: "AIR-DEC-2A128CF8D3BB", result: air_dec_2a128cf8d3bb_result, conditions: vec![("AIR-COND-FC4C836BC163", air_dec_2a128cf8d3bb_c0), ("AIR-COND-1342E8B61A2A", air_dec_2a128cf8d3bb_c1)] });
                if air_dec_2a128cf8d3bb_result {
                    // AEROST-ID: AIR-STMT-38804274281F
                    trace.statements.push("AIR-STMT-38804274281F");
                    let air_dec_4f304d4ee080_c0 = inputs.essential_power_available;
                    let air_dec_4f304d4ee080_result = inputs.essential_power_available;
                    trace.decisions.push(DecisionEvent { id: "AIR-DEC-4F304D4EE080", result: air_dec_4f304d4ee080_result, conditions: vec![("AIR-COND-160BD1733874", air_dec_4f304d4ee080_c0)] });
                    if air_dec_4f304d4ee080_result {
                        // AEROST-ID: AIR-STMT-2695352AEE34
                        trace.statements.push("AIR-STMT-2695352AEE34");
                        state.state = SupervisorState::Critical;
                    } else {
                        // AEROST-ID: AIR-STMT-806A417F5C3F
                        trace.statements.push("AIR-STMT-806A417F5C3F");
                        state.state = SupervisorState::Lockout;
                    }
                } else {
                    let air_dec_f26bba9634d5_c0 = inputs.main_bus_critical;
                    let air_dec_f26bba9634d5_result = inputs.main_bus_critical;
                    trace.decisions.push(DecisionEvent { id: "AIR-DEC-F26BBA9634D5", result: air_dec_f26bba9634d5_result, conditions: vec![("AIR-COND-50A7117E5BB5", air_dec_f26bba9634d5_c0)] });
                    if air_dec_f26bba9634d5_result {
                        // AEROST-ID: AIR-STMT-22037CE76C48
                        trace.statements.push("AIR-STMT-22037CE76C48");
                        state.state = SupervisorState::Critical;
                    } else {
                        let air_dec_93a18b494a46_c0 = inputs.contactor_mismatch_persisted;
                        let air_dec_93a18b494a46_c1 = inputs.main_bus_warning_persisted;
                        let air_dec_93a18b494a46_c2 = !inputs.battery_a_healthy;
                        let air_dec_93a18b494a46_c3 = !inputs.battery_b_healthy;
                        let air_dec_93a18b494a46_result = inputs.contactor_mismatch_persisted || inputs.main_bus_warning_persisted || !inputs.battery_a_healthy || !inputs.battery_b_healthy;
                        trace.decisions.push(DecisionEvent { id: "AIR-DEC-93A18B494A46", result: air_dec_93a18b494a46_result, conditions: vec![("AIR-COND-592BFC643C74", air_dec_93a18b494a46_c0), ("AIR-COND-2F99F25465C8", air_dec_93a18b494a46_c1), ("AIR-COND-F4060203942C", air_dec_93a18b494a46_c2), ("AIR-COND-B3AB2C8B1E72", air_dec_93a18b494a46_c3)] });
                        if air_dec_93a18b494a46_result {
                            // AEROST-ID: AIR-STMT-138B96328901
                            trace.statements.push("AIR-STMT-138B96328901");
                            state.state = SupervisorState::Degraded;
                        } else {
                            let air_dec_0cebb87e5827_c0 = inputs.reset_authorized;
                            let air_dec_0cebb87e5827_c1 = inputs.recovery_stable;
                            let air_dec_0cebb87e5827_c2 = !inputs.return_energy_insufficient;
                            let air_dec_0cebb87e5827_c3 = inputs.essential_power_available;
                            let air_dec_0cebb87e5827_result = inputs.reset_authorized && inputs.recovery_stable && !inputs.return_energy_insufficient && inputs.essential_power_available;
                            trace.decisions.push(DecisionEvent { id: "AIR-DEC-0CEBB87E5827", result: air_dec_0cebb87e5827_result, conditions: vec![("AIR-COND-48A098CCEFFC", air_dec_0cebb87e5827_c0), ("AIR-COND-FAFFD9146AC0", air_dec_0cebb87e5827_c1), ("AIR-COND-4C5A67F31175", air_dec_0cebb87e5827_c2), ("AIR-COND-8A52A49CD6CF", air_dec_0cebb87e5827_c3)] });
                            if air_dec_0cebb87e5827_result {
                                // AEROST-ID: AIR-STMT-D79FB6C6FBA5
                                trace.statements.push("AIR-STMT-D79FB6C6FBA5");
                                state.state = SupervisorState::Normal;
                                // AEROST-ID: AIR-STMT-BCA1050F6F69
                                trace.statements.push("AIR-STMT-BCA1050F6F69");
                                state.blocking_fault_latched = false;
                            } else {
                            }
                        }
                    }
                }
            },
            SupervisorState::Lockout => {
                trace.case_arms.push("AIR-STMT-22EA36CE7782::LOCKOUT");
                // AEROST-ID: AIR-STMT-8FBA964424C9
                trace.statements.push("AIR-STMT-8FBA964424C9");
                let air_dec_3769441570c5_c0 = inputs.reset_authorized;
                let air_dec_3769441570c5_c1 = inputs.recovery_stable;
                let air_dec_3769441570c5_c2 = !inputs.main_bus_critical;
                let air_dec_3769441570c5_c3 = !inputs.contactor_mismatch_persisted;
                let air_dec_3769441570c5_c4 = !inputs.main_bus_warning_persisted;
                let air_dec_3769441570c5_c5 = !inputs.return_energy_insufficient;
                let air_dec_3769441570c5_c6 = inputs.battery_a_healthy;
                let air_dec_3769441570c5_c7 = inputs.battery_b_healthy;
                let air_dec_3769441570c5_c8 = inputs.essential_power_available;
                let air_dec_3769441570c5_result = inputs.reset_authorized && inputs.recovery_stable && !inputs.main_bus_critical && !inputs.contactor_mismatch_persisted && !inputs.main_bus_warning_persisted && !inputs.return_energy_insufficient && (inputs.battery_a_healthy || inputs.battery_b_healthy) && inputs.essential_power_available;
                trace.decisions.push(DecisionEvent { id: "AIR-DEC-3769441570C5", result: air_dec_3769441570c5_result, conditions: vec![("AIR-COND-E3220C881F3F", air_dec_3769441570c5_c0), ("AIR-COND-2D0D9A9B15DB", air_dec_3769441570c5_c1), ("AIR-COND-14721A8DD0AF", air_dec_3769441570c5_c2), ("AIR-COND-418210273076", air_dec_3769441570c5_c3), ("AIR-COND-97DBB6731217", air_dec_3769441570c5_c4), ("AIR-COND-CC11C4447B85", air_dec_3769441570c5_c5), ("AIR-COND-FA89E0B9D778", air_dec_3769441570c5_c6), ("AIR-COND-7475F8D3D8FD", air_dec_3769441570c5_c7), ("AIR-COND-2C0CE59B2B64", air_dec_3769441570c5_c8)] });
                if air_dec_3769441570c5_result {
                    // AEROST-ID: AIR-STMT-C5D5741BE9B0
                    trace.statements.push("AIR-STMT-C5D5741BE9B0");
                    state.state = SupervisorState::Normal;
                    // AEROST-ID: AIR-STMT-E7022F914D29
                    trace.statements.push("AIR-STMT-E7022F914D29");
                    state.blocking_fault_latched = false;
                } else {
                }
            },
        }
    } else {
        // AEROST-ID: AIR-STMT-E745A7945A20
        trace.statements.push("AIR-STMT-E745A7945A20");
        state.blocking_fault_latched = true;
    }
    // AEROST-ID: AIR-STMT-0603DAD4493D
    trace.statements.push("AIR-STMT-0603DAD4493D");
    let air_dec_0ae9e0f52239_c0 = inputs.contactor_mismatch_persisted;
    let air_dec_0ae9e0f52239_c1 = state.state == SupervisorState::Critical;
    let air_dec_0ae9e0f52239_c2 = state.state == SupervisorState::Lockout;
    let air_dec_0ae9e0f52239_result = inputs.contactor_mismatch_persisted || state.state == SupervisorState::Critical || state.state == SupervisorState::Lockout;
    trace.decisions.push(DecisionEvent { id: "AIR-DEC-0AE9E0F52239", result: air_dec_0ae9e0f52239_result, conditions: vec![("AIR-COND-3AFC47255EBC", air_dec_0ae9e0f52239_c0), ("AIR-COND-21E225A519E1", air_dec_0ae9e0f52239_c1), ("AIR-COND-75BCDA7E7E54", air_dec_0ae9e0f52239_c2)] });
    if air_dec_0ae9e0f52239_result {
        // AEROST-ID: AIR-STMT-A7916E79B9DE
        trace.statements.push("AIR-STMT-A7916E79B9DE");
        state.blocking_fault_latched = true;
    } else {
    }
    // AEROST-ID: AIR-STMT-DD5316804F59
    trace.statements.push("AIR-STMT-DD5316804F59");
    outputs.payload_permit = false;
    // AEROST-ID: AIR-STMT-9F20ED2E03E8
    trace.statements.push("AIR-STMT-9F20ED2E03E8");
    outputs.shed_nonessential_loads = true;
    // AEROST-ID: AIR-STMT-49A6537C2F51
    trace.statements.push("AIR-STMT-49A6537C2F51");
    outputs.isolate_battery_a = false;
    // AEROST-ID: AIR-STMT-89CEA56742DD
    trace.statements.push("AIR-STMT-89CEA56742DD");
    outputs.isolate_battery_b = false;
    // AEROST-ID: AIR-STMT-39F8E8639950
    trace.statements.push("AIR-STMT-39F8E8639950");
    outputs.return_to_home_request = false;
    // AEROST-ID: AIR-STMT-55E6AE17D2D3
    trace.statements.push("AIR-STMT-55E6AE17D2D3");
    outputs.immediate_landing_request = false;
    // AEROST-ID: AIR-STMT-63250DD6E3B2
    trace.statements.push("AIR-STMT-63250DD6E3B2");
    outputs.mission_progression_permit = false;
    // AEROST-ID: AIR-STMT-FF1C6D4C2F66
    trace.statements.push("AIR-STMT-FF1C6D4C2F66");
    outputs.blocking_power_fault = state.blocking_fault_latched;
    // AEROST-ID: AIR-STMT-029FD17D66EA
    trace.statements.push("AIR-STMT-029FD17D66EA");
    outputs.supervisor_state = state.state;
    // AEROST-ID: AIR-STMT-A2C5E796C1C9
    trace.statements.push("AIR-STMT-A2C5E796C1C9");
    match state.state {
        SupervisorState::Initializing => {
            trace.case_arms.push("AIR-STMT-A2C5E796C1C9::INITIALIZING");
            // AEROST-ID: AIR-STMT-22DB7E868852
            trace.statements.push("AIR-STMT-22DB7E868852");
            outputs.payload_permit = false;
        },
        SupervisorState::Normal => {
            trace.case_arms.push("AIR-STMT-A2C5E796C1C9::NORMAL");
            // AEROST-ID: AIR-STMT-DF1C16A6A5C0
            trace.statements.push("AIR-STMT-DF1C16A6A5C0");
            outputs.payload_permit = true;
            // AEROST-ID: AIR-STMT-73145824122F
            trace.statements.push("AIR-STMT-73145824122F");
            outputs.shed_nonessential_loads = false;
            // AEROST-ID: AIR-STMT-3C3A46196002
            trace.statements.push("AIR-STMT-3C3A46196002");
            outputs.mission_progression_permit = true;
        },
        SupervisorState::EnergyConservation => {
            trace.case_arms.push("AIR-STMT-A2C5E796C1C9::ENERGY_CONSERVATION");
            // AEROST-ID: AIR-STMT-4FDB5B749A90
            trace.statements.push("AIR-STMT-4FDB5B749A90");
            outputs.return_to_home_request = inputs.return_energy_insufficient;
        },
        SupervisorState::Degraded => {
            trace.case_arms.push("AIR-STMT-A2C5E796C1C9::DEGRADED");
            // AEROST-ID: AIR-STMT-C5DFEB3D124D
            trace.statements.push("AIR-STMT-C5DFEB3D124D");
            outputs.return_to_home_request = true;
            // AEROST-ID: AIR-STMT-E2A1F642F5D8
            trace.statements.push("AIR-STMT-E2A1F642F5D8");
            outputs.isolate_battery_a = !inputs.battery_a_healthy && inputs.battery_b_healthy;
            // AEROST-ID: AIR-STMT-0992AE421B6B
            trace.statements.push("AIR-STMT-0992AE421B6B");
            outputs.isolate_battery_b = !inputs.battery_b_healthy && inputs.battery_a_healthy;
        },
        SupervisorState::Critical => {
            trace.case_arms.push("AIR-STMT-A2C5E796C1C9::CRITICAL");
            // AEROST-ID: AIR-STMT-D0CA7CC162F7
            trace.statements.push("AIR-STMT-D0CA7CC162F7");
            outputs.blocking_power_fault = true;
            // AEROST-ID: AIR-STMT-3A8D9B1590D7
            trace.statements.push("AIR-STMT-3A8D9B1590D7");
            outputs.return_to_home_request = true;
            // AEROST-ID: AIR-STMT-BC40D66589B3
            trace.statements.push("AIR-STMT-BC40D66589B3");
            outputs.immediate_landing_request = true;
        },
        SupervisorState::RecoveryPending => {
            trace.case_arms.push("AIR-STMT-A2C5E796C1C9::RECOVERY_PENDING");
            // AEROST-ID: AIR-STMT-A218C155F879
            trace.statements.push("AIR-STMT-A218C155F879");
            outputs.blocking_power_fault = true;
        },
        SupervisorState::Lockout => {
            trace.case_arms.push("AIR-STMT-A2C5E796C1C9::LOCKOUT");
            // AEROST-ID: AIR-STMT-005040901B77
            trace.statements.push("AIR-STMT-005040901B77");
            outputs.blocking_power_fault = true;
            // AEROST-ID: AIR-STMT-A9758B660C0C
            trace.statements.push("AIR-STMT-A9758B660C0C");
            outputs.immediate_landing_request = true;
        },
    }
    // AEROST-ID: AIR-STMT-33396C3EF0F2
    trace.statements.push("AIR-STMT-33396C3EF0F2");
    let air_dec_b12405b9c306_c0 = !inputs.input_set_valid;
    let air_dec_b12405b9c306_result = !inputs.input_set_valid;
    trace.decisions.push(DecisionEvent { id: "AIR-DEC-B12405B9C306", result: air_dec_b12405b9c306_result, conditions: vec![("AIR-COND-8B529D83F7A1", air_dec_b12405b9c306_c0)] });
    if air_dec_b12405b9c306_result {
        // AEROST-ID: AIR-STMT-67D0F41981FD
        trace.statements.push("AIR-STMT-67D0F41981FD");
        outputs.payload_permit = false;
        // AEROST-ID: AIR-STMT-A35A91CC01C4
        trace.statements.push("AIR-STMT-A35A91CC01C4");
        outputs.shed_nonessential_loads = true;
        // AEROST-ID: AIR-STMT-82C7DCC99C3A
        trace.statements.push("AIR-STMT-82C7DCC99C3A");
        outputs.mission_progression_permit = false;
        // AEROST-ID: AIR-STMT-F00E2F162F63
        trace.statements.push("AIR-STMT-F00E2F162F63");
        outputs.isolate_battery_a = false;
        // AEROST-ID: AIR-STMT-5C48844DF386
        trace.statements.push("AIR-STMT-5C48844DF386");
        outputs.isolate_battery_b = false;
        // AEROST-ID: AIR-STMT-A340B58A2404
        trace.statements.push("AIR-STMT-A340B58A2404");
        outputs.blocking_power_fault = true;
        // AEROST-ID: AIR-STMT-61651B39CDB1
        trace.statements.push("AIR-STMT-61651B39CDB1");
        outputs.return_to_home_request = !inputs.flight_phase_landing;
        // AEROST-ID: AIR-STMT-073DB8810B0E
        trace.statements.push("AIR-STMT-073DB8810B0E");
        outputs.immediate_landing_request = inputs.flight_phase_landing || !inputs.essential_power_available;
    } else {
    }
    // AEROST-ID: AIR-STMT-B196FBA75D16
    trace.statements.push("AIR-STMT-B196FBA75D16");
    let air_dec_df6b93d358c8_c0 = inputs.payload_overcurrent;
    let air_dec_df6b93d358c8_result = inputs.payload_overcurrent;
    trace.decisions.push(DecisionEvent { id: "AIR-DEC-DF6B93D358C8", result: air_dec_df6b93d358c8_result, conditions: vec![("AIR-COND-A3A3B37A7589", air_dec_df6b93d358c8_c0)] });
    if air_dec_df6b93d358c8_result {
        // AEROST-ID: AIR-STMT-B3B2BA12518A
        trace.statements.push("AIR-STMT-B3B2BA12518A");
        outputs.payload_permit = false;
        // AEROST-ID: AIR-STMT-01D476F0FDE3
        trace.statements.push("AIR-STMT-01D476F0FDE3");
        outputs.shed_nonessential_loads = true;
    } else {
    }
    let mut normal_commit_inhibited = false;
    if blocking_runtime_fault {
        normal_commit_inhibited = true;
        state.blocking_fault_latched = true;
        outputs.payload_permit = false;
        outputs.shed_nonessential_loads = true;
        outputs.isolate_battery_a = false;
        outputs.isolate_battery_b = false;
        outputs.return_to_home_request = false;
        outputs.immediate_landing_request = false;
        outputs.mission_progression_permit = false;
        outputs.blocking_power_fault = true;
        outputs.supervisor_state = state.state;
        trace.diagnostics.push("AEROST-RUNTIME-BLOCKING-FAULT");
    }
    if state != resident { trace.diagnostics.push("AEROST-STATE-TRANSITION"); }
    if state.blocking_fault_latched == true { trace.diagnostics.push("AEROST-BLOCKING-FAULT-LATCHED"); }
    CycleResult { retained: state, outputs, normal_commit_inhibited, trace }
}

