//! Generated by AEROST from executable AIR. Do not edit.
#![forbid(unsafe_code)]

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CommunicationLinkState {
    Initializing,
    Nominal,
    Degraded,
    LostLink,
    RecoveryPending,
    Lockout,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Inputs {
    pub input_set_valid: bool,
    pub initialization_complete: bool,
    pub primary_link_available: bool,
    pub secondary_link_available: bool,
    pub link_quality_degraded: bool,
    pub link_loss_persisted: bool,
    pub recovery_stable: bool,
    pub reset_authorized: bool,
    pub command_channel_authenticated: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Outputs {
    pub command_permit: bool,
    pub use_primary_link: bool,
    pub use_secondary_link: bool,
    pub degraded_link_indication: bool,
    pub lost_link_procedure_request: bool,
    pub return_to_home_request: bool,
    pub mission_progression_permit: bool,
    pub blocking_link_fault: bool,
    pub supervisor_state: CommunicationLinkState,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Retained {
    pub state: CommunicationLinkState,
    pub link_fault_latched: bool,
}

impl Default for Inputs {
    fn default() -> Self {
        Self {
            input_set_valid: false,
            initialization_complete: false,
            primary_link_available: false,
            secondary_link_available: false,
            link_quality_degraded: false,
            link_loss_persisted: false,
            recovery_stable: false,
            reset_authorized: false,
            command_channel_authenticated: false,
        }
    }
}

impl Default for Outputs {
    fn default() -> Self {
        Self {
            command_permit: false,
            use_primary_link: false,
            use_secondary_link: false,
            degraded_link_indication: false,
            lost_link_procedure_request: false,
            return_to_home_request: false,
            mission_progression_permit: false,
            blocking_link_fault: false,
            supervisor_state: CommunicationLinkState::Initializing,
        }
    }
}

impl Default for Retained {
    fn default() -> Self {
        Self {
            state: CommunicationLinkState::Initializing,
            link_fault_latched: false,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct DecisionEvent { pub id: &'static str, pub result: bool, pub conditions: Vec<(&'static str, bool)> }
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Trace { pub statements: Vec<&'static str>, pub decisions: Vec<DecisionEvent>, pub case_arms: Vec<&'static str>, pub diagnostics: Vec<&'static str> }
#[derive(Clone, Debug, PartialEq)]
pub struct CycleResult { pub retained: Retained, pub outputs: Outputs, pub normal_commit_inhibited: bool, pub trace: Trace }

pub fn step(mut state: Retained, inputs: &Inputs, blocking_runtime_fault: bool) -> CycleResult {
    let resident = state.clone();
    let mut outputs = Outputs::default();
    let mut trace = Trace::default();
    // AEROST-ID: AIR-STMT-AC5A8184A44E
    trace.statements.push("AIR-STMT-AC5A8184A44E");
    let air_dec_bf704a123803_c0 = inputs.input_set_valid;
    let air_dec_bf704a123803_result = inputs.input_set_valid;
    trace.decisions.push(DecisionEvent { id: "AIR-DEC-BF704A123803", result: air_dec_bf704a123803_result, conditions: vec![("AIR-COND-71AF59F91436", air_dec_bf704a123803_c0)] });
    if air_dec_bf704a123803_result {
        // AEROST-ID: AIR-STMT-7FE4FD402DDD
        trace.statements.push("AIR-STMT-7FE4FD402DDD");
        match state.state {
            CommunicationLinkState::Initializing => {
                trace.case_arms.push("AIR-STMT-7FE4FD402DDD::INITIALIZING");
                // AEROST-ID: AIR-STMT-8747F897C058
                trace.statements.push("AIR-STMT-8747F897C058");
                let air_dec_e11528f772d0_c0 = inputs.initialization_complete;
                let air_dec_e11528f772d0_c1 = inputs.command_channel_authenticated;
                let air_dec_e11528f772d0_c2 = inputs.primary_link_available;
                let air_dec_e11528f772d0_c3 = inputs.secondary_link_available;
                let air_dec_e11528f772d0_result = inputs.initialization_complete && inputs.command_channel_authenticated && (inputs.primary_link_available || inputs.secondary_link_available);
                trace.decisions.push(DecisionEvent { id: "AIR-DEC-E11528F772D0", result: air_dec_e11528f772d0_result, conditions: vec![("AIR-COND-7CE862BD5FCD", air_dec_e11528f772d0_c0), ("AIR-COND-BED7779F4424", air_dec_e11528f772d0_c1), ("AIR-COND-64F15C3C5A02", air_dec_e11528f772d0_c2), ("AIR-COND-7E9750C7D61B", air_dec_e11528f772d0_c3)] });
                if air_dec_e11528f772d0_result {
                    // AEROST-ID: AIR-STMT-94A658201069
                    trace.statements.push("AIR-STMT-94A658201069");
                    state.state = CommunicationLinkState::Nominal;
                } else {
                    let air_dec_3c4e9ebbecbb_c0 = inputs.initialization_complete;
                    let air_dec_3c4e9ebbecbb_result = inputs.initialization_complete;
                    trace.decisions.push(DecisionEvent { id: "AIR-DEC-3C4E9EBBECBB", result: air_dec_3c4e9ebbecbb_result, conditions: vec![("AIR-COND-C55DA00B442B", air_dec_3c4e9ebbecbb_c0)] });
                    if air_dec_3c4e9ebbecbb_result {
                        // AEROST-ID: AIR-STMT-6D50A2C7A880
                        trace.statements.push("AIR-STMT-6D50A2C7A880");
                        state.state = CommunicationLinkState::Lockout;
                    } else {
                    }
                }
            },
            CommunicationLinkState::Nominal => {
                trace.case_arms.push("AIR-STMT-7FE4FD402DDD::NOMINAL");
                // AEROST-ID: AIR-STMT-767D388028B1
                trace.statements.push("AIR-STMT-767D388028B1");
                let air_dec_f15fb827c5c1_c0 = inputs.link_loss_persisted;
                let air_dec_f15fb827c5c1_c1 = !inputs.primary_link_available;
                let air_dec_f15fb827c5c1_c2 = !inputs.secondary_link_available;
                let air_dec_f15fb827c5c1_result = inputs.link_loss_persisted || !inputs.primary_link_available && !inputs.secondary_link_available;
                trace.decisions.push(DecisionEvent { id: "AIR-DEC-F15FB827C5C1", result: air_dec_f15fb827c5c1_result, conditions: vec![("AIR-COND-4089AB0D6750", air_dec_f15fb827c5c1_c0), ("AIR-COND-793843FC2D65", air_dec_f15fb827c5c1_c1), ("AIR-COND-7320AD49DCC7", air_dec_f15fb827c5c1_c2)] });
                if air_dec_f15fb827c5c1_result {
                    // AEROST-ID: AIR-STMT-99435E75414B
                    trace.statements.push("AIR-STMT-99435E75414B");
                    state.state = CommunicationLinkState::LostLink;
                } else {
                    let air_dec_cd85fb02eb72_c0 = inputs.link_quality_degraded;
                    let air_dec_cd85fb02eb72_c1 = !inputs.primary_link_available;
                    let air_dec_cd85fb02eb72_c2 = !inputs.secondary_link_available;
                    let air_dec_cd85fb02eb72_c3 = !inputs.command_channel_authenticated;
                    let air_dec_cd85fb02eb72_result = inputs.link_quality_degraded || !inputs.primary_link_available || !inputs.secondary_link_available || !inputs.command_channel_authenticated;
                    trace.decisions.push(DecisionEvent { id: "AIR-DEC-CD85FB02EB72", result: air_dec_cd85fb02eb72_result, conditions: vec![("AIR-COND-18C272CB4C29", air_dec_cd85fb02eb72_c0), ("AIR-COND-057158D99548", air_dec_cd85fb02eb72_c1), ("AIR-COND-8A22B1F9BCF6", air_dec_cd85fb02eb72_c2), ("AIR-COND-52B17750FFC7", air_dec_cd85fb02eb72_c3)] });
                    if air_dec_cd85fb02eb72_result {
                        // AEROST-ID: AIR-STMT-363BB5F7BABB
                        trace.statements.push("AIR-STMT-363BB5F7BABB");
                        state.state = CommunicationLinkState::Degraded;
                    } else {
                    }
                }
            },
            CommunicationLinkState::Degraded => {
                trace.case_arms.push("AIR-STMT-7FE4FD402DDD::DEGRADED");
                // AEROST-ID: AIR-STMT-858AECC5C883
                trace.statements.push("AIR-STMT-858AECC5C883");
                let air_dec_c15397ed3f0a_c0 = inputs.link_loss_persisted;
                let air_dec_c15397ed3f0a_c1 = !inputs.primary_link_available;
                let air_dec_c15397ed3f0a_c2 = !inputs.secondary_link_available;
                let air_dec_c15397ed3f0a_result = inputs.link_loss_persisted || !inputs.primary_link_available && !inputs.secondary_link_available;
                trace.decisions.push(DecisionEvent { id: "AIR-DEC-C15397ED3F0A", result: air_dec_c15397ed3f0a_result, conditions: vec![("AIR-COND-5740B33F484E", air_dec_c15397ed3f0a_c0), ("AIR-COND-E43A0D3C92E1", air_dec_c15397ed3f0a_c1), ("AIR-COND-48160B62BAEF", air_dec_c15397ed3f0a_c2)] });
                if air_dec_c15397ed3f0a_result {
                    // AEROST-ID: AIR-STMT-D18352A49A33
                    trace.statements.push("AIR-STMT-D18352A49A33");
                    state.state = CommunicationLinkState::LostLink;
                } else {
                    let air_dec_78827340a084_c0 = inputs.recovery_stable;
                    let air_dec_78827340a084_c1 = inputs.primary_link_available;
                    let air_dec_78827340a084_c2 = inputs.secondary_link_available;
                    let air_dec_78827340a084_c3 = inputs.command_channel_authenticated;
                    let air_dec_78827340a084_c4 = !inputs.link_quality_degraded;
                    let air_dec_78827340a084_result = inputs.recovery_stable && inputs.primary_link_available && inputs.secondary_link_available && inputs.command_channel_authenticated && !inputs.link_quality_degraded;
                    trace.decisions.push(DecisionEvent { id: "AIR-DEC-78827340A084", result: air_dec_78827340a084_result, conditions: vec![("AIR-COND-9197056085FE", air_dec_78827340a084_c0), ("AIR-COND-E3E3882462AC", air_dec_78827340a084_c1), ("AIR-COND-CF3B9050C31B", air_dec_78827340a084_c2), ("AIR-COND-15CC65FC0325", air_dec_78827340a084_c3), ("AIR-COND-E4D08AF310FC", air_dec_78827340a084_c4)] });
                    if air_dec_78827340a084_result {
                        // AEROST-ID: AIR-STMT-B5D2E3D5D648
                        trace.statements.push("AIR-STMT-B5D2E3D5D648");
                        state.state = CommunicationLinkState::RecoveryPending;
                    } else {
                    }
                }
            },
            CommunicationLinkState::LostLink => {
                trace.case_arms.push("AIR-STMT-7FE4FD402DDD::LOST_LINK");
                // AEROST-ID: AIR-STMT-485408464A38
                trace.statements.push("AIR-STMT-485408464A38");
                let air_dec_c4b7b27e0075_c0 = inputs.recovery_stable;
                let air_dec_c4b7b27e0075_c1 = inputs.primary_link_available;
                let air_dec_c4b7b27e0075_c2 = inputs.secondary_link_available;
                let air_dec_c4b7b27e0075_c3 = inputs.command_channel_authenticated;
                let air_dec_c4b7b27e0075_result = inputs.recovery_stable && (inputs.primary_link_available || inputs.secondary_link_available) && inputs.command_channel_authenticated;
                trace.decisions.push(DecisionEvent { id: "AIR-DEC-C4B7B27E0075", result: air_dec_c4b7b27e0075_result, conditions: vec![("AIR-COND-B72FED13362D", air_dec_c4b7b27e0075_c0), ("AIR-COND-07D709DB7F51", air_dec_c4b7b27e0075_c1), ("AIR-COND-198A1B1EE4CF", air_dec_c4b7b27e0075_c2), ("AIR-COND-B856C7AB9AF6", air_dec_c4b7b27e0075_c3)] });
                if air_dec_c4b7b27e0075_result {
                    // AEROST-ID: AIR-STMT-EAED9383D904
                    trace.statements.push("AIR-STMT-EAED9383D904");
                    state.state = CommunicationLinkState::RecoveryPending;
                } else {
                }
            },
            CommunicationLinkState::RecoveryPending => {
                trace.case_arms.push("AIR-STMT-7FE4FD402DDD::RECOVERY_PENDING");
                // AEROST-ID: AIR-STMT-7980321B634C
                trace.statements.push("AIR-STMT-7980321B634C");
                let air_dec_080d6c64b501_c0 = inputs.link_loss_persisted;
                let air_dec_080d6c64b501_c1 = !inputs.primary_link_available;
                let air_dec_080d6c64b501_c2 = !inputs.secondary_link_available;
                let air_dec_080d6c64b501_result = inputs.link_loss_persisted || !inputs.primary_link_available && !inputs.secondary_link_available;
                trace.decisions.push(DecisionEvent { id: "AIR-DEC-080D6C64B501", result: air_dec_080d6c64b501_result, conditions: vec![("AIR-COND-38A77753C9BB", air_dec_080d6c64b501_c0), ("AIR-COND-816F5A87C37C", air_dec_080d6c64b501_c1), ("AIR-COND-D115437E2970", air_dec_080d6c64b501_c2)] });
                if air_dec_080d6c64b501_result {
                    // AEROST-ID: AIR-STMT-412CB814D6AB
                    trace.statements.push("AIR-STMT-412CB814D6AB");
                    state.state = CommunicationLinkState::LostLink;
                } else {
                    let air_dec_cab019d5c1a2_c0 = inputs.link_quality_degraded;
                    let air_dec_cab019d5c1a2_c1 = !inputs.primary_link_available;
                    let air_dec_cab019d5c1a2_c2 = !inputs.secondary_link_available;
                    let air_dec_cab019d5c1a2_c3 = !inputs.command_channel_authenticated;
                    let air_dec_cab019d5c1a2_result = inputs.link_quality_degraded || !inputs.primary_link_available || !inputs.secondary_link_available || !inputs.command_channel_authenticated;
                    trace.decisions.push(DecisionEvent { id: "AIR-DEC-CAB019D5C1A2", result: air_dec_cab019d5c1a2_result, conditions: vec![("AIR-COND-569BA6F8A5A4", air_dec_cab019d5c1a2_c0), ("AIR-COND-CAE388844A15", air_dec_cab019d5c1a2_c1), ("AIR-COND-5A5880ACA2D4", air_dec_cab019d5c1a2_c2), ("AIR-COND-324E98A1F836", air_dec_cab019d5c1a2_c3)] });
                    if air_dec_cab019d5c1a2_result {
                        // AEROST-ID: AIR-STMT-94E73C63A6B1
                        trace.statements.push("AIR-STMT-94E73C63A6B1");
                        state.state = CommunicationLinkState::Degraded;
                    } else {
                        let air_dec_e8e90b8fbb1d_c0 = inputs.reset_authorized;
                        let air_dec_e8e90b8fbb1d_c1 = inputs.recovery_stable;
                        let air_dec_e8e90b8fbb1d_result = inputs.reset_authorized && inputs.recovery_stable;
                        trace.decisions.push(DecisionEvent { id: "AIR-DEC-E8E90B8FBB1D", result: air_dec_e8e90b8fbb1d_result, conditions: vec![("AIR-COND-01D9F1A011F4", air_dec_e8e90b8fbb1d_c0), ("AIR-COND-39E43926C012", air_dec_e8e90b8fbb1d_c1)] });
                        if air_dec_e8e90b8fbb1d_result {
                            // AEROST-ID: AIR-STMT-D2B8560811F4
                            trace.statements.push("AIR-STMT-D2B8560811F4");
                            state.state = CommunicationLinkState::Nominal;
                            // AEROST-ID: AIR-STMT-E8FB0D862FC7
                            trace.statements.push("AIR-STMT-E8FB0D862FC7");
                            state.link_fault_latched = false;
                        } else {
                        }
                    }
                }
            },
            CommunicationLinkState::Lockout => {
                trace.case_arms.push("AIR-STMT-7FE4FD402DDD::LOCKOUT");
                // AEROST-ID: AIR-STMT-56C257A8ED2F
                trace.statements.push("AIR-STMT-56C257A8ED2F");
                let air_dec_9dee36c5ad49_c0 = inputs.reset_authorized;
                let air_dec_9dee36c5ad49_c1 = inputs.recovery_stable;
                let air_dec_9dee36c5ad49_c2 = inputs.primary_link_available;
                let air_dec_9dee36c5ad49_c3 = inputs.secondary_link_available;
                let air_dec_9dee36c5ad49_c4 = inputs.command_channel_authenticated;
                let air_dec_9dee36c5ad49_result = inputs.reset_authorized && inputs.recovery_stable && (inputs.primary_link_available || inputs.secondary_link_available) && inputs.command_channel_authenticated;
                trace.decisions.push(DecisionEvent { id: "AIR-DEC-9DEE36C5AD49", result: air_dec_9dee36c5ad49_result, conditions: vec![("AIR-COND-3BDDB32D00D8", air_dec_9dee36c5ad49_c0), ("AIR-COND-441C1085C0BC", air_dec_9dee36c5ad49_c1), ("AIR-COND-28BAD0606931", air_dec_9dee36c5ad49_c2), ("AIR-COND-E82911A939C0", air_dec_9dee36c5ad49_c3), ("AIR-COND-32A566D26462", air_dec_9dee36c5ad49_c4)] });
                if air_dec_9dee36c5ad49_result {
                    // AEROST-ID: AIR-STMT-414DE608629A
                    trace.statements.push("AIR-STMT-414DE608629A");
                    state.state = CommunicationLinkState::RecoveryPending;
                } else {
                }
            },
        }
    } else {
        // AEROST-ID: AIR-STMT-C9718E3467B7
        trace.statements.push("AIR-STMT-C9718E3467B7");
        state.link_fault_latched = true;
    }
    // AEROST-ID: AIR-STMT-14393895584B
    trace.statements.push("AIR-STMT-14393895584B");
    let air_dec_03ae84856b0f_c0 = state.state == CommunicationLinkState::LostLink;
    let air_dec_03ae84856b0f_c1 = state.state == CommunicationLinkState::Lockout;
    let air_dec_03ae84856b0f_result = state.state == CommunicationLinkState::LostLink || state.state == CommunicationLinkState::Lockout;
    trace.decisions.push(DecisionEvent { id: "AIR-DEC-03AE84856B0F", result: air_dec_03ae84856b0f_result, conditions: vec![("AIR-COND-1144A3531C95", air_dec_03ae84856b0f_c0), ("AIR-COND-28DB73F26FB0", air_dec_03ae84856b0f_c1)] });
    if air_dec_03ae84856b0f_result {
        // AEROST-ID: AIR-STMT-C9E2D8A022F0
        trace.statements.push("AIR-STMT-C9E2D8A022F0");
        state.link_fault_latched = true;
    } else {
    }
    // AEROST-ID: AIR-STMT-E339B90EFC08
    trace.statements.push("AIR-STMT-E339B90EFC08");
    outputs.command_permit = false;
    // AEROST-ID: AIR-STMT-6501D1DD4935
    trace.statements.push("AIR-STMT-6501D1DD4935");
    outputs.use_primary_link = false;
    // AEROST-ID: AIR-STMT-0BD1DE8869A3
    trace.statements.push("AIR-STMT-0BD1DE8869A3");
    outputs.use_secondary_link = false;
    // AEROST-ID: AIR-STMT-8C6ADF7B028D
    trace.statements.push("AIR-STMT-8C6ADF7B028D");
    outputs.degraded_link_indication = true;
    // AEROST-ID: AIR-STMT-88790EE5C92A
    trace.statements.push("AIR-STMT-88790EE5C92A");
    outputs.lost_link_procedure_request = false;
    // AEROST-ID: AIR-STMT-39F8E8639950
    trace.statements.push("AIR-STMT-39F8E8639950");
    outputs.return_to_home_request = false;
    // AEROST-ID: AIR-STMT-63250DD6E3B2
    trace.statements.push("AIR-STMT-63250DD6E3B2");
    outputs.mission_progression_permit = false;
    // AEROST-ID: AIR-STMT-52D3D83A6B1A
    trace.statements.push("AIR-STMT-52D3D83A6B1A");
    outputs.blocking_link_fault = state.link_fault_latched;
    // AEROST-ID: AIR-STMT-029FD17D66EA
    trace.statements.push("AIR-STMT-029FD17D66EA");
    outputs.supervisor_state = state.state;
    // AEROST-ID: AIR-STMT-48AD42CC4969
    trace.statements.push("AIR-STMT-48AD42CC4969");
    match state.state {
        CommunicationLinkState::Initializing => {
            trace.case_arms.push("AIR-STMT-48AD42CC4969::INITIALIZING");
            // AEROST-ID: AIR-STMT-69E1B6FD8A70
            trace.statements.push("AIR-STMT-69E1B6FD8A70");
            outputs.degraded_link_indication = true;
        },
        CommunicationLinkState::Nominal => {
            trace.case_arms.push("AIR-STMT-48AD42CC4969::NOMINAL");
            // AEROST-ID: AIR-STMT-9351A2ED74F5
            trace.statements.push("AIR-STMT-9351A2ED74F5");
            outputs.command_permit = true;
            // AEROST-ID: AIR-STMT-E1EB5BEBC18A
            trace.statements.push("AIR-STMT-E1EB5BEBC18A");
            outputs.use_primary_link = true;
            // AEROST-ID: AIR-STMT-D794F39C615E
            trace.statements.push("AIR-STMT-D794F39C615E");
            outputs.degraded_link_indication = false;
            // AEROST-ID: AIR-STMT-3C3A46196002
            trace.statements.push("AIR-STMT-3C3A46196002");
            outputs.mission_progression_permit = true;
        },
        CommunicationLinkState::Degraded => {
            trace.case_arms.push("AIR-STMT-48AD42CC4969::DEGRADED");
            // AEROST-ID: AIR-STMT-A9D3D2D2DF01
            trace.statements.push("AIR-STMT-A9D3D2D2DF01");
            outputs.command_permit = inputs.command_channel_authenticated && (inputs.primary_link_available || inputs.secondary_link_available);
            // AEROST-ID: AIR-STMT-7E9943E265E4
            trace.statements.push("AIR-STMT-7E9943E265E4");
            outputs.use_primary_link = inputs.primary_link_available;
            // AEROST-ID: AIR-STMT-F1D9BC0787E8
            trace.statements.push("AIR-STMT-F1D9BC0787E8");
            outputs.use_secondary_link = !inputs.primary_link_available && inputs.secondary_link_available;
            // AEROST-ID: AIR-STMT-38E622DEB1D6
            trace.statements.push("AIR-STMT-38E622DEB1D6");
            outputs.degraded_link_indication = true;
            // AEROST-ID: AIR-STMT-C5DFEB3D124D
            trace.statements.push("AIR-STMT-C5DFEB3D124D");
            outputs.return_to_home_request = true;
        },
        CommunicationLinkState::LostLink => {
            trace.case_arms.push("AIR-STMT-48AD42CC4969::LOST_LINK");
            // AEROST-ID: AIR-STMT-1A656E3E8CF7
            trace.statements.push("AIR-STMT-1A656E3E8CF7");
            outputs.blocking_link_fault = true;
            // AEROST-ID: AIR-STMT-1D79B159A9EB
            trace.statements.push("AIR-STMT-1D79B159A9EB");
            outputs.lost_link_procedure_request = true;
            // AEROST-ID: AIR-STMT-3A8D9B1590D7
            trace.statements.push("AIR-STMT-3A8D9B1590D7");
            outputs.return_to_home_request = true;
        },
        CommunicationLinkState::RecoveryPending => {
            trace.case_arms.push("AIR-STMT-48AD42CC4969::RECOVERY_PENDING");
            // AEROST-ID: AIR-STMT-94E7C31BC9A9
            trace.statements.push("AIR-STMT-94E7C31BC9A9");
            outputs.blocking_link_fault = true;
            // AEROST-ID: AIR-STMT-082E6D18F5E4
            trace.statements.push("AIR-STMT-082E6D18F5E4");
            outputs.degraded_link_indication = true;
        },
        CommunicationLinkState::Lockout => {
            trace.case_arms.push("AIR-STMT-48AD42CC4969::LOCKOUT");
            // AEROST-ID: AIR-STMT-794114E2D92B
            trace.statements.push("AIR-STMT-794114E2D92B");
            outputs.blocking_link_fault = true;
            // AEROST-ID: AIR-STMT-A72BEC58DCCD
            trace.statements.push("AIR-STMT-A72BEC58DCCD");
            outputs.lost_link_procedure_request = true;
        },
    }
    // AEROST-ID: AIR-STMT-88B97ACB290A
    trace.statements.push("AIR-STMT-88B97ACB290A");
    let air_dec_7e345c4af44f_c0 = !inputs.input_set_valid;
    let air_dec_7e345c4af44f_result = !inputs.input_set_valid;
    trace.decisions.push(DecisionEvent { id: "AIR-DEC-7E345C4AF44F", result: air_dec_7e345c4af44f_result, conditions: vec![("AIR-COND-944024658FE0", air_dec_7e345c4af44f_c0)] });
    if air_dec_7e345c4af44f_result {
        // AEROST-ID: AIR-STMT-2FCFC820C326
        trace.statements.push("AIR-STMT-2FCFC820C326");
        outputs.command_permit = false;
        // AEROST-ID: AIR-STMT-115F523F0F94
        trace.statements.push("AIR-STMT-115F523F0F94");
        outputs.use_primary_link = false;
        // AEROST-ID: AIR-STMT-FAE0764112FF
        trace.statements.push("AIR-STMT-FAE0764112FF");
        outputs.use_secondary_link = false;
        // AEROST-ID: AIR-STMT-B42D768495B4
        trace.statements.push("AIR-STMT-B42D768495B4");
        outputs.degraded_link_indication = true;
        // AEROST-ID: AIR-STMT-A93938A69075
        trace.statements.push("AIR-STMT-A93938A69075");
        outputs.lost_link_procedure_request = true;
        // AEROST-ID: AIR-STMT-7F61268DFDAA
        trace.statements.push("AIR-STMT-7F61268DFDAA");
        outputs.return_to_home_request = true;
        // AEROST-ID: AIR-STMT-82C7DCC99C3A
        trace.statements.push("AIR-STMT-82C7DCC99C3A");
        outputs.mission_progression_permit = false;
        // AEROST-ID: AIR-STMT-93079F21BA07
        trace.statements.push("AIR-STMT-93079F21BA07");
        outputs.blocking_link_fault = true;
    } else {
    }
    let mut normal_commit_inhibited = false;
    if blocking_runtime_fault {
        normal_commit_inhibited = true;
        state.link_fault_latched = true;
        outputs.command_permit = false;
        outputs.use_primary_link = false;
        outputs.use_secondary_link = false;
        outputs.degraded_link_indication = true;
        outputs.lost_link_procedure_request = true;
        outputs.return_to_home_request = true;
        outputs.mission_progression_permit = false;
        outputs.blocking_link_fault = true;
        outputs.supervisor_state = state.state;
        trace.diagnostics.push("AEROST-RUNTIME-BLOCKING-FAULT");
    }
    if state != resident { trace.diagnostics.push("AEROST-STATE-TRANSITION"); }
    if state.link_fault_latched == true { trace.diagnostics.push("AEROST-LINK-FAULT-LATCHED"); }
    CycleResult { retained: state, outputs, normal_commit_inhibited, trace }
}

